# Generated by Django 4.2.4 on 2023-08-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OSSData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.TextField(verbose_name="Site ID")),
                ("source_id", models.TextField(verbose_name="Source ID")),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("notes", models.TextField(verbose_name="Notes")),
                ("status", models.TextField(verbose_name="Status")),
            ],
            options={
                "db_table": "oss",
                "managed": False,
            },
        ),
    ]
