# Generated by Django 4.2.4 on 2023-08-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ossdata",
            table="oss_data",
        ),
    ]
