name: Django Tests

on:
  push:
    branches: [ "main", "cat-dev", "kasey-dev" ]
  pull_request:
    branches: [ "main", "cat-dev", "kasey-dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: hatch build
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install hatch
        hatch shell
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Build with hatch
      run: |
        hatch build -c 
    - name: Test with pytest
      run: |
        pytest